// Quiz data — 5 questions per session, 29 sessions = 145 questions
// answer: "A"|"B"|"C"|"D"  |  callback: false or session number(s)

const quizData = [
  {
    session: 1, title: "Regulate, relate, reason",
    questions: [
      { q: "The RRR triangle mirrors Maslow's hierarchy in which key way?", opts: ["A) Both were created by the same psychologist in the 1950s", "B) Both say foundational needs must be secure before higher needs", "C) Both organise human needs into exactly five separate tiers", "D) Both are concerned mainly with raising pupils' academic achievement"], answer: "B", callback: false },
      { q: "In the neurosequential model, 'neurosequential' means:", opts: ["A) That neurons must fire in a fixed, repeated sequence during learning", "B) That brain functions develop and activate bottom-up, lowest first", "C) That classroom learning has to follow a prescribed order", "D) That all children develop at the same neurological rate"], answer: "B", callback: false },
      { q: "Which best describes why 'Reason' sits at the top of the triangle?", opts: ["A) Reasoning is simply the most important skill to teach", "B) Reasoning evolved most recently and develops last of all", "C) Reasoning is by far the easiest of the three tiers to reach", "D) Reasoning should be a practitioner's very first goal"], answer: "B", callback: false },
      { q: "A student is visibly upset and refusing to engage. According to RRR, the first priority is:", opts: ["A) Explaining the consequences of their behaviour clearly", "B) Calling their parent or carer without delay", "C) Helping them regulate and settle their nervous system", "D) Referring them to the SENCO for further assessment"], answer: "C", callback: false },
      { q: "The Regulate tier of the triangle corresponds to which part of the brain?", opts: ["A) The cortex, where higher reasoning takes place", "B) The limbic system, acting entirely on its own", "C) The brain stem and the lower brain structures", "D) The prefrontal cortex, just behind the forehead"], answer: "C", callback: false }
    ]
  },
  {
    session: 2, title: "Meet your brain",
    questions: [
      { q: "The brain stem is primarily responsible for:", opts: ["A) Storing emotional memory and forming early attachment bonds", "B) Producing language and complex reasoning", "C) Life-sustaining functions like pulse and breathing", "D) Planning, judgement and weighing decisions"], answer: "C", callback: false },
      { q: "The limbic system reaches maturity at approximately:", opts: ["A) 5–7 years old", "B) 10–13 years old", "C) 18 years old", "D) 25 years old"], answer: "B", callback: false },
      { q: "The prefrontal cortex — the seat of logical reasoning — reaches full maturity at approximately:", opts: ["A) 16 years old", "B) 18 years old", "C) 21 years old", "D) 25 years old"], answer: "D", callback: false },
      { q: "Brain development follows a pattern described as:", opts: ["A) Top-down — cortex first, brain stem develops last", "B) Outside-in — developing from the cortex inward", "C) Bottom-up — brain stem first, cortex last", "D) Simultaneously — all regions develop together at once"], answer: "C", callback: false },
      { q: "[Callback: s1] According to the RRR triangle, which brain region must be sufficiently settled before reasoning is accessible?", opts: ["A) Only the cortex really needs to be active", "B) The brain stem and limbic system must settle first", "C) The cortex can override the lower regions when needed", "D) All of the regions function independently of each other"], answer: "B", callback: 1 }
    ]
  },
  {
    session: 3, title: "The lookout system",
    questions: [
      { q: "The 'lookout system' refers to:", opts: ["A) A school monitoring system for at-risk pupils", "B) Brain pathways that scan the environment for threat", "C) A teacher's duty to watch for safeguarding concerns", "D) The brain system that regulates the sleep cycle"], answer: "B", callback: false },
      { q: "Polyvagal theory identifies which response as active when we feel safe?", opts: ["A) Fight or flight — the body's mobilising response", "B) Freeze — the body's bracing, on-hold response", "C) Social engagement — calm, connected, able to think", "D) Shutdown — the body's collapse-and-disconnect response"], answer: "C", callback: false },
      { q: "A student who seems constantly on alert, scanning the room and startling at small sounds, is most likely showing signs of:", opts: ["A) An attention deficit affecting focus and concentration", "B) A hypervigilant lookout system primed to find danger", "C) Boredom with the content of this particular lesson", "D) Poor impulse control and a lack of self-discipline"], answer: "B", callback: false },
      { q: "When the lookout system detects a potential threat, which response is typically activated?", opts: ["A) Social engagement and calm connection", "B) Open curiosity about what is happening", "C) A fight, flight or freeze response", "D) Relaxed, settled and comfortable attention"], answer: "C", callback: false },
      { q: "[Callback: s2] The lookout system is primarily associated with which part of the brain?", opts: ["A) The cortex, the brain's main thinking region", "B) The limbic system and the brain stem", "C) The prefrontal cortex, behind the forehead", "D) The cerebellum, at the back of the brain"], answer: "B", callback: 2 }
    ]
  },
  {
    session: 4, title: "The stress response in school",
    questions: [
      { q: "At the start of the clip Jess is regulated and able to explain what she needs (to keep her friend Warren safe). What does the neurosequential model tell us about the trajectory of the incident from here?", opts: ["A) Escalation was inevitable the moment she raised a concern", "B) How the adults responded, not Jess, shaped what happened next", "C) It proves her reasoning was fully available to her throughout", "D) Restraint was always going to be the only safe outcome here"], answer: "B", callback: false },
      { q: "Jess is hypervigilant — scanning, on guard, repeating her concern. In the model, hypervigilance is a sign that:", opts: ["A) She is being manipulative to avoid a consequence", "B) She is calm but is simply being argumentative", "C) Her stress response is active and reasoning is offline", "D) She is socially engaged and quite ready to negotiate calmly now"], answer: "C", callback: false },
      { q: "[Callback: s3] Jess's lookout system is already signalling threat as staff approach. Which response are the adults most likely to meet?", opts: ["A) Curiosity and openness to their instructions", "B) Social engagement and ready cooperation with staff", "C) Fight, flight or freeze, not social engagement", "D) Calm reasoning, if the rules are explained clearly"], answer: "C", callback: 3 },
      { q: "By the end of the clip neither Jess nor the staff are regulated. Why does the adults' own dysregulation matter most in the neurosequential model?", opts: ["A) It doesn't — only the student's regulation really matters", "B) Visible adult stress shows the student it is serious", "C) A dysregulated adult cannot co-regulate anyone else", "D) It speeds the student's return to clear reasoning"], answer: "C", callback: false },
      { q: "Jess is cornered and intimidated before being restrained. The clip's 'simple solution' is natural curiosity and listening. In Regulate → Relate → Reason terms, what went wrong?", opts: ["A) Staff needed firmer boundaries and quicker consequences", "B) Staff used control before regulating and relating first", "C) Nothing went wrong — staff followed the model correctly", "D) More adults were needed to enforce quicker compliance"], answer: "B", callback: false }
    ]
  },
  {
    session: 5, title: "Early trauma & the brain",
    questions: [
      { q: "Chronic activation of the stress response in early childhood leads to:", opts: ["A) A steadily stronger and more resilient nervous system over the years", "B) An over-sensitised lookout system that detects threat too readily", "C) No lasting changes once the child reaches adulthood", "D) Steadily improving emotional regulation as they grow up"], answer: "B", callback: false },
      { q: "Dr Nadine Burke Harris's research on ACEs found that childhood trauma:", opts: ["A) Has only limited impact if addressed before age ten", "B) Affects health, behaviour and learning across the lifespan", "C) Affects learning but not long-term physical health", "D) Matters only for those children who experienced direct physical abuse"], answer: "B", callback: false },
      { q: "'Hypervigilance' — a common consequence of early trauma — means:", opts: ["A) Being highly attentive and academically very focused at all times", "B) Constant alertness, scanning even safe places for danger", "C) An overactive immune system response to stress", "D) Heightened sensitivity to sensory stimuli only"], answer: "B", callback: false },
      { q: "A student who has experienced early trauma may escalate at a trivial trigger because:", opts: ["A) They are deliberately testing the adult's patience and boundaries", "B) Their system treats low-level signals as serious threats", "C) They lack any moral understanding of consequences", "D) They have simply never been taught how to behave"], answer: "B", callback: false },
      { q: "[Callback: s1, s2, s3, s4] Which sequence best describes how early trauma affects a student's access to the RRR triangle?", opts: ["A) Trauma improves access to Reason by building resilience", "B) Trauma over-sensitises the lookout system, blocking the higher tiers", "C) Trauma only makes the Relate tier — building relationships — much harder", "D) Trauma impairs the Reason tier and cortical function only"], answer: "B", callback: [1, 2, 3, 4] }
    ]
  },
  {
    session: 6, title: "Regulating the body",
    questions: [
      { q: "Mindfulness is best described as:", opts: ["A) Clearing the mind of all thought to reach blankness", "B) Paying attention to the present, with curiosity not judgement", "C) A relaxation technique guaranteed to make you feel calm and relaxed", "D) Thinking positively so that difficult feelings go away"], answer: "B", callback: false },
      { q: "A common misconception is that mindfulness means stopping or emptying your thoughts. In fact, mindfulness is:", opts: ["A) Forcing the mind to go completely silent and still", "B) Pushing away any thought that feels uncomfortable", "C) Noticing thoughts and feelings as they come and go", "D) Distracting yourself until the difficult thoughts fade"], answer: "C", callback: false },
      { q: "Practising mindfulness 'without judgement' means:", opts: ["A) Deciding whether each thought is good or bad", "B) Observing what you notice with acceptance, not self-criticism", "C) Deliberately ignoring uncomfortable feelings until they finally stop", "D) Allowing only the pleasant thoughts to remain present"], answer: "B", callback: false },
      { q: "Why does mindfulness support self-regulation? Because it:", opts: ["A) Removes stress from your life once and for all", "B) Builds the habit of noticing rising stress early", "C) Replaces the body's need to calm its own system", "D) Keeps the thinking brain online however threatened you feel"], answer: "B", callback: false },
      { q: "[Callback: s4] Mindful awareness of your own body matters most for a practitioner because:", opts: ["A) It impresses students with how calm you appear", "B) Noticing your own stress early lets you regulate first", "C) It guarantees students will copy your slow breathing", "D) It lets consequences be applied faster during incidents"], answer: "B", callback: 4 }
    ]
  },
  {
    session: 7, title: "Why relating comes next",
    questions: [
      { q: "Social engagement becomes possible only when:", opts: ["A) A student has learned the right coping strategies", "B) The nervous system signals enough safety to connect", "C) A positive relationship has formed over several months", "D) Academic expectations have been temporarily reduced"], answer: "B", callback: false },
      { q: "[Callback: s1] Session 1 introduced the Regulate → Relate → Reason sequence. According to that model, why does Relate come before Reason?", opts: ["A) Relationships matter more than academic learning does", "B) A student must feel safe and connected before reasoning", "C) Reasoning is too advanced for most Inclusion Base pupils", "D) Relating is simply quicker to deliver than reasoning"], answer: "B", callback: 1 },
      { q: "Why is it counterproductive to focus on building relationship before regulation?", opts: ["A) Relationships take longer to establish than regulation does", "B) A dysregulated student cannot take in relational input", "C) Relationship-building matters less than regulation does", "D) New adults are not trusted until students feel safe"], answer: "B", callback: false },
      { q: "The shift from Regulate to Relate in the RRR triangle is best described as:", opts: ["A) Moving from consequences towards rewards and praise", "B) Moving from managing behaviour to building trust", "C) Moving from physical to more emotional intervention", "D) Moving from individual work to small-group work"], answer: "B", callback: false },
      { q: "[Callback: s3] A student's lookout system has settled after a period of calm. Which shift in their behaviour would you most expect to see as social engagement comes back online?", opts: ["A) An immediate improvement in their academic output", "B) More eye contact, softer posture, openness to talk", "C) Better behaviour with every member of staff at once", "D) A reduced need for any adult support at all"], answer: "B", callback: 3 }
    ]
  },
  {
    session: 8, title: "Empathy vs sympathy",
    questions: [
      { q: "Brené Brown defines empathy as:", opts: ["A) Feeling sorry for someone in a difficult situation", "B) Feeling WITH someone and communicating that connection", "C) Offering practical solutions to their problems efficiently", "D) Keeping professional distance while acknowledging difficulty"], answer: "B", callback: false },
      { q: "The phrase 'empathy fuels connection, sympathy drives disconnection' means:", opts: ["A) Sympathy is harmful and should be avoided entirely", "B) Empathy connects by entering the experience; sympathy distances", "C) Emotional responses are always more helpful than practical ones", "D) Professional relationships should only ever rely on empathy"], answer: "B", callback: false },
      { q: "An 'at least' response is typically unhelpful because:", opts: ["A) It offers a kind of false comfort to the person", "B) It minimises the pain by jumping to the positive", "C) It is usually factually inaccurate in some way", "D) It needs personal knowledge the listener may lack"], answer: "B", callback: false },
      { q: "When someone shares a problem, the most empathetic first response is:", opts: ["A) Offering a clear, workable solution as quickly as you possibly can", "B) Sharing a similar experience of your own to relate", "C) Acknowledging the feeling first — 'that sounds really hard'", "D) Asking clarifying questions to understand it fully"], answer: "C", callback: false },
      { q: "How does the empathy-first approach connect to the Kintsugi philosophy?", opts: ["A) Both involve repairing relationships that have broken down", "B) Both sit with difficulty rather than hiding or fixing it", "C) Both grew out of Japanese philosophical traditions", "D) Both focus on the value of professional distance"], answer: "B", callback: false }
    ]
  },
  {
    session: 9, title: "Why your ego thrives on conflict",
    questions: [
      { q: "Why does a student's defiance in front of the whole class often provoke a stronger reaction in an adult than the same words said privately?", opts: ["A) Public defiance is always a more serious offence than private", "B) The ego feels its status threatened in front of an audience", "C) Students only ever act up to get attention from peers", "D) Private conversations are simply easier to stay calm in"], answer: "B", callback: false },
      { q: "In a confrontation with a pupil, the strong urge to 'have the last word' is best understood as:", opts: ["A) A reasonable need to check the pupil has understood", "B) The ego seeking to win and reassert itself", "C) An effective way of maintaining authority in the room", "D) A clear sign the adult is staying calm and in control"], answer: "B", callback: false },
      { q: "An adult who feels they must be 'right' and win the argument with a defiant pupil is most likely to:", opts: ["A) Strengthen the relationship through honesty and openness", "B) Model really good reasoning for the rest of the class", "C) Win the point but damage the relationship and escalate", "D) Help the pupil develop their own debating skills"], answer: "C", callback: false },
      { q: "'The ego thrives on conflict and pain' means that:", opts: ["A) Some people simply enjoy being difficult with others", "B) The ego strengthens itself through opposition and drama", "C) Conflict is always necessary for genuine personal growth", "D) Pain is the only thing that truly motivates real change"], answer: "B", callback: false },
      { q: "[Callback: s4] When a pupil is publicly defiant, the most effective way to avoid an ego-driven power struggle is to:", opts: ["A) Match their intensity so they know that you mean business", "B) Insist on full compliance before anyone can move on", "C) Step out of the contest and refuse to take the bait", "D) Give an immediate public consequence to restore authority"], answer: "C", callback: 4 }
    ]
  },
  {
    session: 10, title: "Pears Family School",
    questions: [
      { q: "According to the source, what percentage of children who need mental health treatment do not currently receive it?", opts: ["A) 20%", "B) 50%", "C) 80%", "D) 95%"], answer: "C", callback: false },
      { q: "At what age do most adults with mental health issues first begin to show symptoms?", opts: ["A) Before they are 18", "B) After age 21", "C) During early childhood (under 5)", "D) In their late 20s"], answer: "A", callback: false },
      { q: "What is the core hypothesis that makes the Pears Family School model different from mainstream schools?", opts: ["A) Children simply learn better in smaller school buildings", "B) Technology is the key factor in mental health recovery", "C) School change is not sustainable without change at home", "D) Pupils should be taught only by trained researchers"], answer: "C", callback: false },
      { q: "What is a primary benefit of having parents physically present in the school?", opts: ["A) It lets parents take over the teaching duties themselves", "B) Parents see their child in the context of learning", "C) It reduces the cost of providing security at the school", "D) It lets the school finish its classes earlier each day"], answer: "B", callback: false },
      { q: "What is the ultimate goal of merging neuroscience and social science in the new centre?", opts: ["A) To create a school that is entirely automated", "B) To apply discoveries quickly and spread the model widely", "C) To focus only on children who live in London", "D) To replace traditional social work entirely with brain imaging"], answer: "B", callback: false }
    ]
  },
  {
    session: 11, title: "The power of relationships",
    questions: [
      { q: "Why does warm, attuned relational contact help a student regulate?", opts: ["A) It distracts them from whatever is worrying them", "B) It gives the adult far more authority and control over the student", "C) Safe connection releases oxytocin, calming the stress response", "D) It removes the need for any classroom boundaries"], answer: "C", callback: false },
      { q: "Oxytocin is sometimes called the 'bonding' or 'trust' hormone because it:", opts: ["A) Increases alertness so students concentrate harder", "B) Is released by safe connection and lowers threat", "C) Is only ever released during physical exercise", "D) Removes the need for the cortex to be online"], answer: "B", callback: false },
      { q: "When a student feels a genuine sense of safety and belonging in school, the most important effect is that:", opts: ["A) They will from then on always behave perfectly", "B) Academic standards for the class can be raised almost straight away", "C) Their nervous system settles, freeing capacity to learn", "D) They no longer need any adult support at all"], answer: "C", callback: false },
      { q: "How does natural curiosity go hand in hand with relational practice?", opts: ["A) Curiosity is mainly about gathering evidence to justify a consequence", "B) Genuine curiosity — 'what's happening for you?' — signals safety", "C) Curiosity means questioning a student until they comply", "D) Curiosity only matters once a relationship already exists"], answer: "B", callback: false },
      { q: "[Callback: s4] 'Psychological safety' means students feel able to make mistakes, ask for help and be honest. Relational practice builds it because:", opts: ["A) It sets stricter, clearer rules that everyone in the class understands", "B) Consistent, curious, non-judgemental relationships feel safe", "C) It rewards students for taking bold academic risks", "D) It removes all challenge so that nobody can fail"], answer: "B", callback: 4 }
    ]
  },
  {
    session: 12, title: "Relational practice in the classroom",
    questions: [
      { q: "In the Lesson Toolkit, greeting each pupil at the door ('Meet & Greet') is relational practice because it:", opts: ["A) It lets you check uniform before pupils come in", "B) It creates a warm connection that signals safety first", "C) It saves a bit of time at the start of the lesson", "D) It helps you spot which pupils are likely to misbehave today"], answer: "B", callback: false },
      { q: "'Plausible anonymity' — for example, 'I'm only waiting for two people now' — works by:", opts: ["A) Publicly naming the off-task pupils so they correct fast", "B) Prompting pupils to self-correct without being named", "C) Ignoring low-level disruption in the room altogether", "D) Issuing an immediate sanction to the whole group"], answer: "B", callback: false },
      { q: "In the 100% Compliance ladder of corrective responses, which should generally come FIRST?", opts: ["A) A quick public corrective that names the pupil", "B) An individual private warning to the pupil", "C) A non-verbal cue, such as a silent gesture", "D) A sanction applied to the pupil straight away"], answer: "C", callback: false },
      { q: "Why does the corrective sequence start with non-verbal and group prompts and keep public, named correction to a minimum?", opts: ["A) Because adults should avoid correcting pupils wherever possible", "B) Because the least-invasive approach protects the relationship", "C) Because public correction is forbidden by school policy", "D) Because non-verbal cues are the only method that works"], answer: "B", callback: false },
      { q: "[Callback: s9] 'Live in the now — today's a fresh start' and 'assume the best' help avoid power struggles because they:", opts: ["A) They lower expectations for pupils who struggled yesterday", "B) They let the adult drop grievances and meet pupils warmly", "C) They mean that past behaviour is never actually addressed", "D) They remove the need for any correction at all in lessons"], answer: "B", callback: 9 }
    ]
  },
  {
    session: 13, title: "Why reasoning comes last",
    questions: [
      { q: "The cortex is the last brain region to mature and the first to be affected by stress. This is sometimes described as:", opts: ["A) The cortical vulnerability paradox", "B) Last online, first offline — explaining why reasoning is both the highest aspiration and the most fragile capacity", "C) The executive function ceiling", "D) The developmental lag hypothesis"], answer: "B", callback: false },
      { q: "A student who 'knows the rules but can't follow them' in moments of distress is most likely experiencing:", opts: ["A) Deliberate defiance", "B) Cortical access failure — they know what they should do but cannot access that knowledge when the lookout system is activated", "C) A learning difficulty affecting rule retention", "D) Inconsistent boundary-setting at home"], answer: "B", callback: false },
      { q: "Which condition is necessary for the cortex to function effectively?", opts: ["A) High motivation and clear goals", "B) Regulation and sufficient felt safety — the lower brain must be settled before the upper brain is accessible", "C) Intelligence and prior knowledge", "D) A structured and quiet learning environment"], answer: "B", callback: false },
      { q: "The Reason tier of the RRR triangle can only be built on:", opts: ["A) Academic readiness alone", "B) Stable regulation AND established relationship — both lower tiers must be in place", "C) Motivation and aspiration", "D) Parental support and engagement"], answer: "B", callback: false },
      { q: "[Callback: s2, s4] A teacher asks a student to write a reflective account immediately after a difficult incident. What is the most likely outcome?", opts: ["A) The student will reflect honestly because they remember the incident clearly", "B) The student cannot produce meaningful reflection until their cortex is back online — the task should wait until they are within their window", "C) Written reflection is always more effective immediately after an event", "D) The outcome depends entirely on the student's emotional intelligence"], answer: "B", callback: [2, 4] }
    ]
  },
  {
    session: 14, title: "What is metacognition?",
    questions: [
      { q: "The EEF Toolkit rates metacognition and self-regulation as offering approximately how many months of additional progress?", opts: ["A) 3 months", "B) 5 months", "C) 7+ months — one of the highest-rated strategies in the toolkit", "D) 2 months"], answer: "C", callback: false },
      { q: "Metacognition is best defined as:", opts: ["A) Learning strategies used during revision", "B) Awareness and regulation of one's own thinking — monitoring, evaluating and adjusting cognitive processes", "C) The ability to memorise large amounts of information", "D) Critical thinking applied to academic content"], answer: "B", callback: false },
      { q: "A metacognitively skilled student approaching a new task will first ask:", opts: ["A) 'Is this going to be in the exam?'", "B) 'Am I ready to learn this? What do I already know? Which strategy fits this type of learning?'", "C) 'How long will this take me?'", "D) 'Can I work with someone else on this?'"], answer: "B", callback: false },
      { q: "Which of the following is NOT a component of metacognitive skill?", opts: ["A) Monitoring your own understanding as you learn", "B) Selecting strategies based on the type of material", "C) Evaluating whether your current approach is working", "D) Increasing the speed at which you read"], answer: "D", callback: false },
      { q: "[Callback: s13] Why is a student in hyper-arousal unable to benefit from metacognitive strategy coaching in that moment?", opts: ["A) They lack the motivation to engage with strategy instruction", "B) Metacognition requires cortical activity — specifically the planning and monitoring functions of the prefrontal cortex — which are unavailable when the stress response is active", "C) Strategy coaching requires a calm environment, which is a separate issue from regulation", "D) Hyper-arousal improves focus and should theoretically enhance metacognitive activity"], answer: "B", callback: 13 }
    ]
  },
  {
    session: 15, title: "The illusion of mastery",
    questions: [
      { q: "The 'illusion of mastery' occurs because:", opts: ["A) Students deliberately overestimate their knowledge to avoid revision", "B) Exposure to familiar material produces a feeling of fluency that the brain mistakes for durable learning", "C) Teachers provide too much reassurance about performance", "D) Revision methods are poorly taught by schools"], answer: "B", callback: false },
      { q: "Which best demonstrates the illusion of mastery?", opts: ["A) A student who revises and achieves a good grade", "B) A student who re-reads notes, feels confident, then performs poorly on a test", "C) A student who avoids revision and performs poorly", "D) A student who makes flashcards and tests themselves"], answer: "B", callback: false },
      { q: "The working memory digit span exercise demonstrates:", opts: ["A) That working memory is unlimited with practice", "B) That working memory has limited capacity, which affects how much can be processed at once", "C) That digit recall is a reliable indicator of general intelligence", "D) That chunking is ineffective as a memory strategy"], answer: "B", callback: false },
      { q: "Recognising content is NOT the same as being able to recall it. The key difference is:", opts: ["A) Recognition requires less intelligence than recall", "B) Recall requires active retrieval from memory — effortful and strengthening; recognition is passive and produces little memory benefit", "C) Both recognition and recall build equally strong memory traces", "D) Recognition is more reliable in high-stakes assessments"], answer: "B", callback: false },
      { q: "How does the illusion of mastery connect to working memory from session 27?", opts: ["A) They are separate cognitive concepts with no overlap", "B) Working memory's limited capacity means re-reading fills that capacity with familiarity without building retrieval strength; both point to the same cognitive limitation", "C) Working memory improves with age, making the illusion of mastery less relevant for older students", "D) Executive function and metacognition are entirely different domains"], answer: "B", callback: false }
    ]
  },
  {
    session: 16, title: "Am I ready to learn?",
    questions: [
      { q: "The Smart Learning School framework's first stage — 'am I ready?' — asks students to establish:", opts: ["A) Whether they have enough time to revise", "B) The foundations of learning — their physical state, emotional state, and environmental conditions", "C) Which subject they are least confident in", "D) Whether they have all the resources they need"], answer: "B", callback: false },
      { q: "According to the RRR framework, which condition must be met before any learning strategy can be effective?", opts: ["A) High motivation", "B) Sufficient regulation — the cortex must be accessible enough to plan, monitor, and adjust", "C) A quiet environment", "D) Prior knowledge of the content"], answer: "B", callback: false },
      { q: "A student who sits down to revise but finds their mind constantly returning to a social conflict is demonstrating:", opts: ["A) Poor motivation", "B) Normal adolescent distraction", "C) The impact of an activated lookout system — their nervous system is still processing a perceived threat, limiting cortical availability", "D) Working memory overload unrelated to emotional state"], answer: "C", callback: false },
      { q: "'Readiness' in the Smart Learning context includes:", opts: ["A) Academic readiness only — knowing enough to begin", "B) Physical readiness (sleep, food, physical state), emotional readiness (regulation), and environmental readiness", "C) Readiness as assessed by a teacher or tutor", "D) Confidence in the subject matter"], answer: "B", callback: false },
      { q: "[Callback: s6, s13, s14] A student uses box breathing before starting revision. Which pathway does this activate?", opts: ["A) Somatic regulation → parasympathetic activation → cortex comes back online → metacognitive strategies become accessible", "B) Distraction from anxiety → improved confidence → better performance", "C) Physical relaxation → reduced working memory load → improved reading speed", "D) Breathing exercise → positive emotional state → increased motivation"], answer: "A", callback: [6, 13, 14] }
    ]
  },
  {
    session: 17, title: "Choosing the right strategy",
    questions: [
      { q: "'Retrieval practice' involves:", opts: ["A) Re-reading and highlighting notes", "B) Attempting to recall information from memory without looking at the source — the effort of retrieval strengthens the memory trace", "C) Creating visual summaries of learning material", "D) Watching videos to review content"], answer: "B", callback: false },
      { q: "'Spaced practice' is more effective than massed practice (cramming) because:", opts: ["A) It takes less total time", "B) Spacing study sessions with gaps forces the brain to re-retrieve information, strengthening the neural pathway each time", "C) It is less tiring and more sustainable", "D) It covers more material in the same period"], answer: "B", callback: false },
      { q: "'Interleaving' — mixing different topics within a study session — is effective because:", opts: ["A) It prevents boredom during long study sessions", "B) It forces the brain to identify which approach applies to each problem — a deeper form of processing than blocked practice", "C) It reduces the total revision time needed", "D) It works best for creative subjects"], answer: "B", callback: false },
      { q: "For a vocabulary-heavy subject, the most evidence-based recommendation is:", opts: ["A) Re-reading and highlighting key terms", "B) Spaced retrieval practice — testing on vocabulary over increasing intervals", "C) Creating a mind map of all the terms", "D) Writing each term out several times"], answer: "B", callback: false },
      { q: "[Callback: s14, s15, s16] How does choosing the right strategy connect to the readiness check?", opts: ["A) Strategy selection should happen first; readiness is a separate concern", "B) Readiness must come first — no strategy is effective if the cortex is offline; once regulated, the student can metacognitively select the strategy that fits", "C) All strategies work equally well when motivation is high", "D) Readiness and strategy are taught separately and don't interact"], answer: "B", callback: [14, 15, 16] }
    ]
  },
  {
    session: 18, title: "How to practise: the right kind of effort",
    questions: [
      { q: "Robert Bjork's concept of 'desirable difficulty' suggests that:", opts: ["A) Learning should be made as easy as possible to build confidence", "B) Introducing appropriate challenge — difficulty that stretches without overwhelming — produces stronger, more durable learning", "C) Students should always work at the top of their ability range", "D) Difficulty in learning is a sign of poor teaching"], answer: "B", callback: false },
      { q: "The 'beautiful flashcard trap' refers to:", opts: ["A) Using flashcards that are too visually complex", "B) Investing significant effort in creating resources that feel productive but avoid the retrieval struggle that builds lasting memory", "C) Revising content that is already well-known", "D) Using images instead of text on flashcards"], answer: "B", callback: false },
      { q: "Which type of effort produces the strongest memory traces?", opts: ["A) Effort spent making revision materials as organised as possible", "B) The effortful struggle of trying to retrieve something from memory — especially when the answer doesn't come easily", "C) Extended periods of focused re-reading", "D) Collaborative study with peers"], answer: "B", callback: false },
      { q: "A student revises with music and 14 browser tabs open. The most significant problem is:", opts: ["A) The music is distracting", "B) Divided attention reduces encoding depth — the brain cannot form strong memory traces while processing competing stimuli", "C) It is not sustainable over a long session", "D) It signals low motivation to the student themselves"], answer: "B", callback: false },
      { q: "[Callback: s15, s16, s17] How do the illusion of mastery, strategy selection, and the right kind of effort form a connected set?", opts: ["A) They are three independent revision tips", "B) The illusion of mastery explains WHY passive approaches feel good but fail; strategy selection identifies WHAT to do instead; desirable difficulty explains HOW to do it — together they describe the full picture of effective practice", "C) They are three sequential stages in the Smart Learning programme", "D) Only strategy selection and effort level are meaningfully related"], answer: "B", callback: [15, 16, 17] }
    ]
  },
  {
    session: 19, title: "Smart Learning in the ISAP classroom",
    questions: [
      { q: "For a student who has missed significant schooling, the most important foundation before strategy coaching is:", opts: ["A) A detailed assessment of current academic levels", "B) Regulation and relationship — without the first two tiers of RRR, metacognitive strategies cannot take root", "C) Parental consent and an independent learning plan", "D) Clarity on qualification entry requirements"], answer: "B", callback: false },
      { q: "An 'Independent Learning Plan' in ISAP supports the Reason tier by:", opts: ["A) Replacing teacher-led lessons with self-directed study", "B) Giving the student agency and transparency over their own learning journey — metacognition begins with knowing where you are going", "C) Reducing teacher workload for ISAP students", "D) Providing evidence for Ofsted inspections"], answer: "B", callback: false },
      { q: "The 'portfolio of achievement' approach is valuable because:", opts: ["A) It satisfies AQA Unit Award Scheme requirements", "B) It makes visible the learning and capability the student cannot demonstrate through traditional exam performance — it widens what counts as success", "C) It reduces the need for formal qualifications", "D) It provides staff with evidence of their own professional impact"], answer: "B", callback: false },
      { q: "Explaining the 'curriculum journey' to a reintegrating student means:", opts: ["A) Giving them a copy of the scheme of work", "B) Helping them understand where they are in the learning sequence, how skills connect, and that missing pieces can be filled — removing the mystery of the gap", "C) Setting them a catch-up programme of homework", "D) Comparing their progress to that of their peers"], answer: "B", callback: false },
      { q: "[Callback: s10, s13] How does Smart Learning for ISAP students connect to the PEARS Family School model and 'reasoning comes last'?", opts: ["A) They are three separate areas with no shared logic", "B) All three recognise that learning capacity is built from the bottom up — family partnership strengthens Relate, regulation makes the cortex accessible, and only then can Smart Learning strategies produce genuine metacognitive development", "C) Smart Learning is for academic improvement; PEARS is for family engagement — different outcomes", "D) The PEARS model and Smart Learning both prioritise qualification outcomes above relationship"], answer: "B", callback: [10, 13] }
    ]
  },
  {
    session: 20, title: "Teaching for lost learning",
    questions: [
      { q: "The 'catch-up narrative' is counterproductive because:", opts: ["A) It is factually inaccurate in most cases", "B) It positions the student as perpetually behind, creating an identity of deficit that increases anxiety and reduces engagement", "C) It places excessive pressure on teachers", "D) It is inconsistent with the school's SEND policy"], answer: "B", callback: false },
      { q: "'Regulational solutions' for reintegrating students include:", opts: ["A) Extra tutoring sessions and revision resources", "B) Predictable routines, trusted adult check-ins, exit routes, and sensory regulation strategies", "C) Reduced timetables and homework exemptions", "D) Peer mentoring and group work"], answer: "B", callback: false },
      { q: "'Meet and greet' — a key motivational solution in reintegration — works because:", opts: ["A) It gives teachers an opportunity to check uniform and equipment", "B) A warm, personal greeting at the start of the day activates the social engagement system — beginning from a relational place", "C) It ensures the student arrives to lessons on time", "D) It provides an opportunity for a brief academic check-in"], answer: "B", callback: false },
      { q: "Reintegration typically works best when it is:", opts: ["A) Full and immediate — a clean break from the ISAP setting", "B) Phased and supported — allowing the student's nervous system and relationships to adjust gradually", "C) Led entirely by the student's own stated preference", "D) Conditional on sustained behaviour improvement"], answer: "B", callback: false },
      { q: "How do classroom regulation strategies, de-escalation, strokes, and family partnership all contribute to successful reintegration?", opts: ["A) Each addresses a different problem and can be implemented separately", "B) Together they recreate the full RRR scaffold in a mainstream setting: regulated environment + trusted relationships + recognition of progress + family holding the thread at home", "C) Regulation strategies are the only factor with significant impact on reintegration outcomes", "D) Family partnership is only relevant in the ISAP phase, not during reintegration"], answer: "B", callback: false }
    ]
  },
  {
    session: 21, title: "Growth mindset deepdive",
    questions: [
      { q: "Carol Dweck's research found that students with a growth mindset respond to failure by:", opts: ["A) Blaming external factors for the outcome", "B) Seeing failure as information — evidence of what needs more practice, not evidence of fixed inability", "C) Seeking reassurance from trusted adults", "D) Avoiding future situations where failure is possible"], answer: "B", callback: false },
      { q: "The word 'yet' transforms a fixed mindset statement because:", opts: ["A) It makes the statement more polite and less confrontational", "B) It converts a permanent identity ('I can't') into a temporary state ('I can't yet') — opening the path to growth", "C) It is required in all SEND documentation", "D) It frames the challenge as optional rather than required"], answer: "B", callback: false },
      { q: "Praising students for their intelligence (rather than effort) typically results in:", opts: ["A) Increased confidence and academic risk-taking", "B) Students avoiding challenging tasks to protect their intelligence label — a fixed mindset response", "C) Higher academic achievement over time", "D) Greater persistence when tasks become difficult"], answer: "B", callback: false },
      { q: "A growth mindset approach to a student's setback involves:", opts: ["A) Minimising the setback to protect self-esteem", "B) Acknowledging the difficulty, naming what the experience is teaching, and identifying the next step", "C) Comparing the current performance to a previous success", "D) Temporarily removing the student from the challenge"], answer: "B", callback: false },
      { q: "[Callback: s5] How does growth mindset connect to both Kintsugi and the understanding of early trauma?", opts: ["A) The three concepts are unrelated", "B) All three recognise that difficulty and breakage are not the end of the story — trauma shapes but does not define; cracks become the site of repair; setbacks become the material for growth", "C) Kintsugi and growth mindset share Eastern philosophical roots; trauma is a separate clinical domain", "D) Growth mindset applies only to academic settings; Kintsugi and trauma are broader"], answer: "B", callback: 5 }
    ]
  },
  {
    session: 22, title: "Stress, scripts & the reasoning brain",
    questions: [
      { q: "TA 'Drivers' are described as:", opts: ["A) Motivational styles identified in coaching", "B) Compulsive messages absorbed in childhood about what we must do to be acceptable — 'Be Strong', 'Please Others', 'Try Hard', 'Be Perfect', 'Hurry Up'", "C) The goals that drive our professional ambitions", "D) Scripts we use to manage difficult students"], answer: "B", callback: false },
      { q: "A person with a 'Be Strong' Driver at work is most likely to:", opts: ["A) Speak openly about stress and ask for support early", "B) Mask distress, refuse to admit struggling, and continue until a breaking point — the driver forbids vulnerability", "C) Be more resilient than colleagues in the long term", "D) Have a stronger coping toolkit than those with other Drivers"], answer: "B", callback: false },
      { q: "The physiological cost of chronically running a Driver is:", opts: ["A) Minimal — Drivers are adaptive patterns that protect mental health", "B) The body is held in a sustained low-level stress response — the nervous system never gets the rest it needs to restore", "C) Mainly psychological — physical health is not directly affected", "D) Limited to sleep quality and recovery time"], answer: "B", callback: false },
      { q: "A 'script-interrupting strategy' for a 'Please Others' Driver might be:", opts: ["A) Being more assertive with students", "B) Practising saying no to one small request per day — building the muscle of self-priority alongside care for others", "C) Reducing the number of students on your caseload", "D) Attending a formal assertiveness training course"], answer: "B", callback: false },
      { q: "[Callback: s4, s9] How do TA Drivers connect to both the stress response and proactive self-care?", opts: ["A) Drivers are a TA concept and do not connect to physiology", "B) Drivers generate chronic low-level stress activation; proactive self-care is specifically about recovering from this sustained load; without understanding your Drivers, self-care plans are likely to fail", "C) Drivers and stress response are related; self-care is a separate intervention", "D) Only the 'Hurry Up' Driver connects to physiological stress"], answer: "B", callback: [4, 9] }
    ]
  },
  {
    session: 23, title: "Proactive self-care & protecting your joy",
    questions: [
      { q: "The key difference between reactive coping and proactive self-care is:", opts: ["A) Reactive coping involves other people; proactive care is individual", "B) Proactive care is scheduled before depletion; reactive coping responds after the tank is already empty", "C) Reactive coping is evidence-based; proactive care is anecdotal", "D) Proactive care takes significantly more time"], answer: "B", callback: false },
      { q: "The 'Wellness Wheel' is a tool for:", opts: ["A) Tracking student wellbeing data", "B) Assessing the balance across different life areas — identifying where proactive attention is most needed", "C) Identifying staff training needs", "D) Evidencing self-care activity to line managers"], answer: "B", callback: false },
      { q: "'Energy givers' and 'energy takers' are distinguished by:", opts: ["A) Whether an activity is work-related", "B) Whether an activity leaves you with more or less capacity after doing it — not by whether it is enjoyable in the moment", "C) Whether an activity involves other people", "D) Whether an activity is physically active"], answer: "B", callback: false },
      { q: "The most reliable way to ensure a self-care activity actually happens is:", opts: ["A) Telling a colleague about it for accountability", "B) Scheduling it in advance as a non-negotiable appointment — an intention without a diary slot rarely materialises", "C) Choosing activities that require no preparation", "D) Making it a daily habit from the very start"], answer: "B", callback: false },
      { q: "[Callback: s6, s22] How does proactive self-care connect to both the regulation toolkit and the Drivers session?", opts: ["A) They are three separate wellbeing concepts", "B) Regulation skills are the in-the-moment toolkit; understanding your Drivers shows where your particular vulnerabilities lie; proactive self-care is the scheduled maintenance that keeps the system from depleting — all three are needed together", "C) Self-care replaces the need for a regulation toolkit", "D) Drivers are only relevant in therapeutic contexts; regulation and self-care apply at work"], answer: "B", callback: [6, 22] }
    ]
  },
  {
    session: 24, title: "Managing compassion fatigue",
    questions: [
      { q: "Compassion fatigue is best defined as:", opts: ["A) Burnout caused by heavy administrative workload", "B) A state of emotional and physical exhaustion resulting from the cumulative emotional cost of caring for others in distress", "C) A temporary response to a particularly difficult student cohort", "D) Low job satisfaction in high-pressure school environments"], answer: "B", callback: false },
      { q: "Secondary traumatic stress differs from compassion fatigue in that:", opts: ["A) It is always more severe", "B) It refers specifically to trauma responses developed through exposure to other people's traumatic experiences — absorbing what they carry", "C) It affects only clinical and therapeutic professionals", "D) It requires a formal clinical diagnosis"], answer: "B", callback: false },
      { q: "A 'decontamination ritual' — such as changing clothes or a brief walk between work and home — works by:", opts: ["A) Improving physical health through movement or sensory change", "B) Creating a symbolic and sensory boundary between work identity and personal identity — helping the nervous system shift out of 'work mode'", "C) Reducing cortisol through physical activity", "D) Providing time to debrief the day mentally"], answer: "B", callback: false },
      { q: "'Professional detachment' is best described as:", opts: ["A) Emotional distance maintained through formal professional boundaries", "B) Caring deeply about the work while not carrying the emotional weight of every outcome — engaged without being consumed", "C) A clinical skill taught only in therapist training", "D) Not forming personal connections with students or families"], answer: "B", callback: false },
      { q: "[Callback: s23] How do staying steady, peer support culture, and proactive self-care together protect against compassion fatigue?", opts: ["A) Each addresses a different aspect and can be implemented independently", "B) Staying steady prevents acute overwhelm; peer support provides ongoing relational recovery; proactive self-care maintains baseline capacity — they are the three pillars of sustainable practice", "C) Compassion fatigue is an individual issue; only personal strategies help", "D) Peer support is the most important factor; the others are supplementary"], answer: "B", callback: 23 }
    ]
  },
  {
    session: 25, title: "Critical incident deepdive",
    questions: [
      { q: "When deconstructing a critical incident through the RRR lens, the most useful first question is:", opts: ["A) Who was responsible for the incident?", "B) What was each person's regulation state at the start — was the lookout system already activated before the incident began?", "C) What policy was breached and how?", "D) What could the student have done differently?"], answer: "B", callback: false },
      { q: "Walking a critical incident through the Regulate → Relate → Reason sequence reveals:", opts: ["A) Who is most at fault", "B) Where the chain of events could have been interrupted — and at which tier an earlier intervention might have changed the outcome", "C) Which behaviour management policy should be updated", "D) Whether the student should return to the ISAP"], answer: "B", callback: false },
      { q: "Applying the TA layer to a critical incident means examining:", opts: ["A) What each person was privately thinking", "B) Which ego states were active at each stage — and where a crossed transaction escalated rather than de-escalated", "C) Which staff member behaved most appropriately", "D) The student's diagnostic history"], answer: "B", callback: false },
      { q: "'Gold from the crack' — the closing Kintsugi frame for a critical incident debrief — involves:", opts: ["A) Finding someone to praise despite the difficulty", "B) Naming what the team did well, what held people together, and the specific learning to carry forward — making the break itself a source of strength", "C) Filing a positive behaviour report to balance the record", "D) Recognising the student's growth since the incident"], answer: "B", callback: false },
      { q: "[Callback: s4] The BBC3 clip appears for the second time here — now viewed through all three frameworks. What does this reveal that was not visible in session 4?", opts: ["A) The same information — the clip's meaning doesn't change", "B) The full picture: the regulation failure (lookout system, window breached), the relational failure (crossed transactions, no relate before reason), the reasoning failure (cortex unavailable) — and the many earlier intervention points the RRR triangle now makes visible", "C) The student's culpability is clearer with hindsight", "D) The incident is better understood through the safeguarding lens than the RRR lens"], answer: "B", callback: 4 }
    ]
  },
  {
    session: 26, title: "Confidence in supporting others",
    questions: [
      { q: "MHFA is NOT designed to:", opts: ["A) Help the first aider notice signs of distress", "B) Provide a first point of human contact before professional help", "C) Replace professional mental health treatment", "D) Provide peer support between colleagues"], answer: "C", callback: false },
      { q: "The ALGEE model closes with 'Encourage other supports'. This final step acknowledges:", opts: ["A) That professional help is always better than peer support", "B) That recovery is supported by multiple sources — friends, family, activities, community — not just formal services", "C) That the MHFA first aider's role ends at professional referral", "D) That school-based support is insufficient on its own"], answer: "B", callback: false },
      { q: "A 'confidence scale' exercise in MHFA training typically reveals:", opts: ["A) That most staff are already highly confident in supporting others", "B) That common fears are shared — fear of saying the wrong thing, making things worse — and naming these normalises and reduces them", "C) Which staff members need additional formal training", "D) That confidence increases linearly with professional experience"], answer: "B", callback: false },
      { q: "'Good enough' MHFA responses means:", opts: ["A) Settling for less than best practice", "B) Recognising that warm, steady, non-judgmental presence matters more than perfect technique — done well enough is better than not done at all", "C) Reducing quality expectations due to resource constraints", "D) Accepting that some interactions will inevitably go badly"], answer: "B", callback: false },
      { q: "[Callback: s8, s11] Looking across all MHFA sessions, which single sentence best captures the through-line?", opts: ["A) Follow the ALGEE model and you won't go wrong", "B) Be regulated, be human, be present, know your limits — your steady, caring presence is the intervention; everything else supports it", "C) MHFA is primarily about knowing when to refer", "D) The most important skill is active listening"], answer: "B", callback: [8, 11] }
    ]
  },
  {
    session: 27, title: "Professional goals & personal wellness plan",
    questions: [
      { q: "Values-based goal setting differs from outcome-based goal setting in that:", opts: ["A) Values-based goals are easier to achieve", "B) Values-based goals are intrinsically motivated — doing them feels worthwhile because they connect to who you are, not just what you want to achieve", "C) Values-based goals do not require measurable outcomes", "D) Outcome-based goals are always set by managers; values-based goals are self-set"], answer: "B", callback: false },
      { q: "A SMART goal is most likely to be sustained when it is also:", opts: ["A) Ambitious enough to stretch you significantly beyond your comfort zone", "B) Aligned with a core personal value — giving it internal meaning as well as external structure", "C) Agreed with and monitored by a line manager", "D) Broken into daily micro-tasks from day one"], answer: "B", callback: false },
      { q: "'Anchor points' in a wellness plan refer to:", opts: ["A) Moments of structured reflection at the start of each term", "B) Non-negotiable scheduled activities — the fixed points around which flexible activities are organised, preventing self-care being squeezed out", "C) Peer support partners who keep you accountable", "D) The values statements that anchor your professional identity"], answer: "B", callback: false },
      { q: "Anticipating barriers to a wellness plan is important because:", opts: ["A) Barriers can then be blamed when the plan fails", "B) Naming barriers in advance allows you to build contingency strategies — the plan remains viable when life doesn't cooperate", "C) Barriers are always external and unpredictable", "D) Sharing barriers with a colleague increases mutual accountability"], answer: "B", callback: false },
      { q: "[Callback: s23] How do gratitude practice, peer support culture, and proactive self-care together inform a professional wellness plan?", opts: ["A) They are three separate resources that apply to different people", "B) Gratitude provides the daily attentional practice; peer support provides the relational infrastructure; proactive self-care provides the scheduled maintenance — together they are the structure of a sustainable professional year", "C) Wellness plans are primarily individual; peer support is a team intervention", "D) Only proactive self-care is directly relevant to a personal wellness plan"], answer: "B", callback: 23 }
    ]
  },
  {
    session: 28, title: "Letter to my future self",
    questions: [
      { q: "Writing a letter to your future self is a metacognitive act because:", opts: ["A) It requires sustained written concentration", "B) It involves deliberately stepping outside your current experience to observe your own growth, patterns, values and hopes — self-authorship as self-awareness", "C) It is a structured form of journalling with a specific audience", "D) It forces honesty in a way other reflection methods don't"], answer: "B", callback: false },
      { q: "The guided reflection before letter-writing typically asks participants to revisit:", opts: ["A) Their professional development targets from the current year", "B) Challenges survived, growth achieved, connections formed, and hopes for the next year", "C) Student outcomes they are most proud of", "D) Incidents that remained unresolved or difficult"], answer: "B", callback: false },
      { q: "'Sealing the letter' and holding it until the next academic year is significant because:", opts: ["A) It creates a formal record of professional development", "B) It becomes a time capsule — the future self who opens it has been changed by the year between, making the reading itself a growth experience", "C) It provides a written record for appraisal", "D) It prevents the content from being shared with others"], answer: "B", callback: false },
      { q: "Sharing 'one hope' aloud at the close of this session serves which function?", opts: ["A) It provides accountability for the content of the letter", "B) It makes the hope real and relational — spoken in community, witnessed by colleagues, it becomes part of the team's shared story", "C) It helps facilitators assess the impact of the programme", "D) It ensures the session ends on a positive note"], answer: "B", callback: false },
      { q: "[Callback: s14, s21] How does the letter to your future self connect to metacognition, growth mindset, and Kintsugi?", opts: ["A) These are four separate exercises that happen to appear in the same programme", "B) All four converge: self-awareness and growth are ongoing; you are the author of your development; difficulty is the material growth is made from; and the act of looking back and forward — metacognitively, hopefully — is itself the gold", "C) Metacognition is cognitive; growth mindset is motivational; Kintsugi is philosophical — they operate in different domains", "D) Letter-writing is the practical output of the three theoretical frameworks"], answer: "B", callback: [14, 21] }
    ]
  },
  {
    session: 29, title: "Celebration, affirmation & the golden thread",
    questions: [
      { q: "An 'affirmation circle' — where each person writes a specific appreciation on every colleague's sheet — is designed to:", opts: ["A) Provide evidence of positive team culture for inspection", "B) Fill the room with unconditional positive strokes — specific, genuine, witnessed recognition of each person's contribution", "C) Replace formal performance appraisal processes", "D) Identify the team's most valued members"], answer: "B", callback: false },
      { q: "The affirmation circle is a direct application of which TA concept?", opts: ["A) Ego states", "B) Transactions", "C) Strokes — positive unconditional recognition", "D) Drivers"], answer: "C", callback: false },
      { q: "'The team is more beautiful for the breaks it survived together' means:", opts: ["A) The team had a particularly difficult year", "B) The difficulties, disagreements, and hard moments of the year are part of the team's story — and holding together through them is itself the gold", "C) Physical beauty increases through shared hardship", "D) The team should now reflect formally on incidents that went wrong"], answer: "B", callback: false },
      { q: "The term reviews showed that regulation and relationship are prerequisites for reasoning. How does this final session embody all three tiers simultaneously?", opts: ["A) It doesn't — it is a celebration session with no direct learning content", "B) The regulated safety of the group allows deep relational connection (the affirmation circle); from that connected, safe place comes the highest-order reflection — reasoning together about who the team has become", "C) All three tiers are presented sequentially within the session agenda", "D) The tiers are now embedded and no longer need to be named explicitly"], answer: "B", callback: false },
      { q: "[Callback: s1] The programme opened with the question of why regulation comes first. Which answer — now available after 29 sessions — is most complete?", opts: ["A) Because behaviour must be managed before learning can begin", "B) Because the nervous system is the foundation of everything — without safety, relationship cannot form; without relationship, reasoning cannot emerge; and it is only in the highest tier that we become authors of our own story and golden threads in each other's", "C) Because it is what the neurosequential model recommends practitioners prioritise", "D) Because regulation is the simplest tier to begin with in a professional development context"], answer: "B", callback: 1 }
    ]
  }
];

// Helper: get questions for a specific session number
function getSessionQuiz(sessionNum) {
  return quizData.find(s => s.session === sessionNum);
}

// Helper: get all callback questions (i.e. those that reference earlier sessions)
function getCallbackQuestions() {
  const callbacks = [];
  quizData.forEach(s => {
    s.questions.forEach((q, i) => {
      if (q.callback !== false) callbacks.push({ session: s.session, qIndex: i, refs: q.callback });
    });
  });
  return callbacks;
}
